-- Drop tables if they exist to ensure clean slate for refactoring
DROP TABLE IF EXISTS "equipment_calendar" CASCADE;
DROP TABLE IF EXISTS "facility_calendar" CASCADE;
DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "reservation_audit" CASCADE;
DROP TABLE IF EXISTS "approval_logs" CASCADE;
DROP TABLE IF EXISTS "equipment_availabilities" CASCADE;
DROP TABLE IF EXISTS "facility_availabilities" CASCADE;
DROP TABLE IF EXISTS "reservation_items" CASCADE;
DROP TABLE IF EXISTS "reservations" CASCADE;
DROP TABLE IF EXISTS "reservation_statuses" CASCADE;
DROP TABLE IF EXISTS "equipments" CASCADE;
DROP TABLE IF EXISTS "facilities" CASCADE;
DROP TABLE IF EXISTS "buildings" CASCADE;
DROP TABLE IF EXISTS "facility_types" CASCADE;
DROP TABLE IF EXISTS "password_reset_tokens" CASCADE;
DROP TABLE IF EXISTS "admin_tokens" CASCADE;
DROP TABLE IF EXISTS "system_tokens" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "user_preferences" CASCADE; 
DROP TABLE IF EXISTS "ratings" CASCADE; 

-- Drop types
DROP TYPE IF EXISTS user_role_enum CASCADE;
DROP TYPE IF EXISTS approval_action_enum CASCADE;
DROP TYPE IF EXISTS audit_change_enum CASCADE;

-- ========= 1. BUAT TIPE ENUM KUSTOM =========
DO $$ BEGIN
    CREATE TYPE user_role_enum AS ENUM ('admin', 'user');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE approval_action_enum AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE audit_change_enum AS ENUM ('CREATE', 'UPDATE', 'DELETE', 'CANCEL');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ========= 2. BUAT FUNGSI TRIGGER UNTUK UPDATE 'updated_at' =========
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ========= 3. DEFINISI TABEL =========

-- Tabel System Tokens (Global)
CREATE TABLE IF NOT EXISTS "system_tokens" (
  "key" varchar PRIMARY KEY,
  "value" varchar NOT NULL,
  "description" text
);

CREATE TABLE IF NOT EXISTS "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Email removed
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "full_name" varchar NOT NULL,
  "role" user_role_enum NOT NULL DEFAULT 'user',
  "profile_picture_url" varchar,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "last_login_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "facility_types" (
  "type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text
);

CREATE TABLE IF NOT EXISTS "buildings" (
  "building_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "code" varchar, 
  "location_description" text,
  "image_url" varchar,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS set_buildings_timestamp ON "buildings";
CREATE TRIGGER set_buildings_timestamp
BEFORE UPDATE ON "buildings"
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TABLE IF NOT EXISTS "facilities" (
  "facility_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_id" int NOT NULL REFERENCES "facility_types" ("type_id"),
  "building_id" int REFERENCES "buildings" ("building_id") ON DELETE SET NULL,
  "name" varchar NOT NULL,
  "room_number" varchar,
  "capacity" int,
  "floor" int,
  "description" text,
  "layout_description" text,
  "photo_url" varchar, 
  "is_active" boolean DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS set_facilities_timestamp ON "facilities";
CREATE TRIGGER set_facilities_timestamp
BEFORE UPDATE ON "facilities"
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TABLE IF NOT EXISTS "equipments" (
  "equipment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_id" int NOT NULL REFERENCES "facility_types" ("type_id"),
  "name" varchar NOT NULL,
  "location" varchar, 
  "quantity" int NOT NULL DEFAULT 1,
  "description" text,
  "photo_url" varchar,
  "is_active" boolean DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS set_equipments_timestamp ON "equipments";
CREATE TRIGGER set_equipments_timestamp
BEFORE UPDATE ON "equipments"
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TABLE IF NOT EXISTS "reservation_statuses" (
  "status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text
);

CREATE TABLE IF NOT EXISTS "reservations" (
  "reservation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "requester_id" int NOT NULL REFERENCES "users" ("user_id"),
  "status_id" int NOT NULL REFERENCES "reservation_statuses" ("status_id"),
  "purpose" text NOT NULL,
  "attendees" int,
  "proposal_url" varchar,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  "is_canceled" boolean DEFAULT false
);

DROP TRIGGER IF EXISTS set_reservations_timestamp ON "reservations";
CREATE TRIGGER set_reservations_timestamp
BEFORE UPDATE ON "reservations"
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TABLE IF NOT EXISTS "reservation_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" int NOT NULL REFERENCES "reservations" ("reservation_id") ON DELETE CASCADE,
  "facility_id" int REFERENCES "facilities" ("facility_id"),
  "equipment_id" int REFERENCES "equipments" ("equipment_id"),
  "start_datetime" timestamptz NOT NULL,
  "end_datetime" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT "check_valid_datetime_range" CHECK (end_datetime > start_datetime),
  CONSTRAINT "check_item_not_empty" CHECK (facility_id IS NOT NULL OR equipment_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS "approval_logs" (
  "approval_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" int NOT NULL REFERENCES "reservations" ("reservation_id") ON DELETE CASCADE,
  "acted_by" int NOT NULL REFERENCES "users" ("user_id"),
  "action" approval_action_enum NOT NULL,
  "comment" text,
  "acted_at" timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "reservation_audit" (
  "audit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" int NOT NULL REFERENCES "reservations" ("reservation_id") ON DELETE CASCADE,
  "changed_by" int REFERENCES "users" ("user_id"),
  "change_type" audit_change_enum NOT NULL,
  "change_data" jsonb, 
  "changed_at" timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "notifications" (
  "notification_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL REFERENCES "users" ("user_id") ON DELETE CASCADE,
  "reservation_id" int REFERENCES "reservations" ("reservation_id"),
  "title" varchar,
  "message" text,
  "is_read" boolean DEFAULT false,
  "status_id" int REFERENCES "reservation_statuses" ("status_id"),
  "created_at" timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "ratings" (
  "rating_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL REFERENCES "users" ("user_id"),
  "facility_id" int NOT NULL REFERENCES "facilities" ("facility_id"),
  "reservation_id" int NOT NULL REFERENCES "reservations" ("reservation_id"),
  "rating" int NOT NULL CHECK (rating >= 1 AND rating <= 5),
  "review" text,
  "created_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS "idx_facilities_type_id" ON "facilities" ("type_id");
CREATE INDEX IF NOT EXISTS "idx_facilities_building_id" ON "facilities" ("building_id");
CREATE INDEX IF NOT EXISTS "idx_equipments_type_id" ON "equipments" ("type_id");
CREATE INDEX IF NOT EXISTS "idx_reservations_requester_id" ON "reservations" ("requester_id");
CREATE INDEX IF NOT EXISTS "idx_reservations_status_id" ON "reservations" ("status_id");
CREATE INDEX IF NOT EXISTS "idx_reservation_items_reservation_id" ON "reservation_items" ("reservation_id");
CREATE INDEX IF NOT EXISTS "idx_reservation_items_facility_id" ON "reservation_items" ("facility_id");
CREATE INDEX IF NOT EXISTS "idx_reservation_items_start_datetime" ON "reservation_items" ("start_datetime");
CREATE INDEX IF NOT EXISTS "idx_reservation_items_end_datetime" ON "reservation_items" ("end_datetime");
CREATE INDEX IF NOT EXISTS "idx_notifications_user_id" ON "notifications" ("user_id");
