-- Add username to users
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "username" varchar UNIQUE;
-- Update existing users to have a username (fallback to part of email) if needed, 
-- but since we can't easily do substring logic safely across all DB versions efficiently in one line without risk, 
-- we will leave it null for now or let the user handle data migration. 
-- Actually, let's try to set it to email for existing users to avoid unique violation if we enforce NOT NULL later, 
-- but for now allowing NULL is safer for migration.

-- Add recovery_token to users (optional, if we don't use password_reset_tokens table)
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "recovery_token" varchar;

-- Create admin_tokens table
CREATE TABLE IF NOT EXISTS "admin_tokens" (
  "token_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" varchar UNIQUE NOT NULL,
  "is_used" boolean DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "used_at" timestamptz
);

-- Seed some initial admin tokens for testing
INSERT INTO "admin_tokens" ("token") VALUES 
('ADMIN-SECRET-123'),
('ADMIN-POWER-456'),
('SUPER-ADMIN-789')
ON CONFLICT ("token") DO NOTHING;
